# Generated by Django 3.2.3 on 2022-04-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='text',
        ),
    ]
