databases:
  - name: main
    databaseName: main
    user: main

services:
  - type: web
    name: main
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: main
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
